### ISSUE TITLE
Git Flow 적용

### ISSUE THREAD

**Issue by agiletalk** [weirdswift/alarm#2]
[Git Flow](http://nvie.com/posts/a-successful-git-branching-model) 적용해보면 어떨까요?

**Comment by happyEngineer** [comment]
해봅시당~~~  ^^ 근데 이거 클라이언트에서 적용하면 되는거 아닌가요?  서버에도 적용해야 하는 뭔가가 있는건가요?

**Comment by agiletalk** [comment]
서버라면 깃헙 말씀하시는건가요? 보통은 깃헙에는 master, develop 브랜치만 올려두고, 각 개발자는 develop 브랜치를 계속 업데이트 하고 feature 브랜치는 로컬에서 작업하고 develop에 머지한 후에 커밋하는 걸로 알고 있어요~

**Comment by happyEngineer** [comment]
네, 어떻게 적용하는것이 좋을까요? ^^  사실 방법 적으로 어떻게 해야할지를 이야기 해야할것 같은데, 제가 방법을 잘 몰라서요.

**Comment by happyEngineer** [comment]
일단 develop 브렌치 만들어서 올렸습니다. ^^

**Comment by happyEngineer** [comment]
일단 feature-개발 기능 이름.. 이런식으로 추가하면 어떨까 싶은데.. 어떠세요?
기능으로 추가할 것들부터 리스트를 만들어야 할것 같네요.

**Comment by agiletalk** [comment]
SourceTree 쓰신다면 Git Flow 메뉴가 있어서 Feature나 Release, Hotfix를 시작하거나 끝내는 작업을 UI로 다 할 수 있어요~ 그럼 알아서 feature/A, release/1.0 와 같이 브랜치를 알아서 만들어줘요!
